### ISSUE TITLE
Gauge filters: Disable/hide "Add missing _____" filters in a couple of scenarios

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1019]
# Issues
There are a couple of scenarios where it doesn't make sense to offer indicator filters:
1. When none of my indicators have targets set up, it doesn't make sense to filter on indicators missing results and results missing evidence.
2. When at least some of my indicators have targets, but no results are reported yet, it doesn't make sense to filter on results missing evidence.

![image](https://user-images.githubusercontent.com/33670923/50621362-47092b80-0eba-11e9-9959-565f001cc1fa.png)

# Acceptance criteria

## 0% of indicators have targets
- [x] 1. Hide "Add missing results" link
     - [x] 1.1. Disable yellow highlight and click-whole-block-to-filter experience
- [x] 2. Hide "Add missing evidence
     - [x] 2.1. Disable yellow highlight an  click-whole-block-to-filter experience
- [x] 3. Regression check: For the "Indicators with targets" gauge, there are no UX changes -- "Add missing targets" link displays, yellow highlights and filters work as expected.

## Some indicators have targets but 0% of indicators have results
- [x] 1. Hide "Add missing evidence
     - [x] 1.1. Disable yellow highlight and filter link
- [x] 2. Regression checks
     - [x] 2.1. For the "Indicators with targets" gauge, there are no UX changes -- "Add missing targets" link displays, yellow highlights and filters work as expected.
     - [x] 2.2. For the "Indicators with results" gauge, there are no UX changes -- "Add missing results" link displays, yellow highlights and filters work as expected.

**Comment by axoplasm** [comment]
Couple things I noticed on this:

1. Links from homepage to filtered lists still work. e.g. I can click on the empty “Results with Evidence" gauge on “QA Program -- No Results Here” and still see the (empty) filtered list.
2. On the program page: the filter & highlight for "Indicators with Results" is inappropriately hidden, when in fact I do have indicators already defined. e.g. for “QA Program -- No Results Here”

I think the overarching goal here is that *it shouldn’t be possible to get an __empty list__ of indicators for a condition __whose dependency__ is not yet fulfilled.* i.e.:

* I shouldn’t be prompted to add results if I don’t have any targets defined
* I shouldn’t be prompted to add evidence if I don’t have any results entered

**Comment by KennyMonster** [comment]
> 2\. On the program page: the filter & highlight for "Indicators with Results" is inappropriately hidden, when in fact I do have indicators already defined. e.g. for “QA Program -- No Results Here”

This has been resolved in huckleberry.

fc803aa245d10bcc943cc66a7c5f99d7bad782ce

**Comment by axoplasm** [comment]
I need to check on QA but this is still not quite right on the homepage:
![image](https://user-images.githubusercontent.com/169060/52432741-1cfde700-2ac0-11e9-8c39-b5d937a0ac22.png)

Should look like the program page (minus the CTA link):
![image](https://user-images.githubusercontent.com/169060/52432773-32731100-2ac0-11e9-8120-767b01baab35.png)

**Comment by axoplasm** [comment]
…well that was easier than I thought

**Comment by axoplasm** [comment]
See also #1159

**Comment by RickieT** [comment]
Looks like this has been implemented as requested, moving to ready for deploy: 
![1019](https://user-images.githubusercontent.com/23220180/52674277-f8e34100-2ed7-11e9-9f5d-3d8c7bdfa7d8.png)
