### ISSUE TITLE
IPTT Most recent: When value entered exceeds number of periods, display maximum available value

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1629]
**Affects:** Both IPTTs, "Most recent" toggle option.

# Issue
If I enter a "Most recent" value that is higher than the available number of periods we have to display, the system currently reverts to "Show all". While logical from a technical standpoint, it's unexpected from a user perspective... and could come across as a "you're ignoring what I asked for" bug.

# Proposed solution
If I enter a "Most recent" value that is higher than the highest available number of periods we have to display, the system defaults to _that number_ -- the highest available number of periods we have to display. 

To be clear: This solution has no effect on how many periods we display -- it's already "everything". This is strictly about what number we show in the numeric field next to "Most recent".

**Comment by jennyhavah** [comment]
@camgnostic If this is a high level of effort, we can postpone... Or let me know if you have ideas for another approach that's easier to implement.

**Comment by camgnostic** [comment]
@jennyhavah what do we do about the radio buttons in that case?  If a program has ended and has 10 periods, then "most recent 10" is the same as "show all".  Should _both_ radio buttons be checked?  Or just show all but with a number showing in most recent?

**Comment by jennyhavah** [comment]
@camgnostic I'm imagining this to be equivalent to the user having manually entered, precisely, the exact number of available periods.

So I would expect "Most recent" to remain selected. And then the number just magically has the exact number of available periods, as if I'd typed it in.

**Comment by camgnostic** [comment]
K - this does mean the buttons are a little ambiguous.  So just to clarify (novel incoming):

If I have a program with 10 periods, all of which are past, there are three ways I could see the whole program:

1) I click "show all" -> I see all the periods, "show all" radio button is checked.
2) I click "start" and select the first period, I click "end" and select the last period -> I see all the periods, "show all" radio button is checked
3) I click "most recent" and enter 10 (or a number greater than 10) -> I see all the periods, "most recent" radio button is checked, "show all" is _not_ checked, and I see 10 in the most recent box.

This sounds right?

**Comment by jennyhavah** [comment]
@camgnostic Yes, this sounds right.

Can you help me understand how it seems ambiguous, from a user perspective?

**Comment by camgnostic** [comment]
Just - there are situations where all periods are shown, but "show all" is not checked.  In the sense of the show all radio button as indicating "I clicked show all" this way makes sense, but there's also a sense that the show all radio button indicates "all periods are shown" - and in that case it's confusing that it isn't checked despite all periods being shown.  It might just be me overcomplicating things.  Either way, I can meet these criteria.

**Comment by jennyhavah** [comment]
I'm seeing a number of unexpected behaviors:

1. "Show all" form field label is no longer clickable.

2. When I switch from "Show all" to Most Recent, it auto-populates the number of fields... Which, as per #1619, is not what we want. (We want it to wait until you type in a value.)

3. When I create a "Show all" **_Target vs Actuals_** report and then switch between programs, sometimes it automatically switches to "Most recent" with a blank number. I can't quite figure out the pattern. But my expectation is, that if I move between programs, and I've got "Show all" selected, then it remains "Show all" until I actively choose "Most recent".

4. When I select a "Most recent" value and then switch to another program, the "Most recent" field goes blank and... I'm not sure what I'm looking at. It should preserve the number of periods and, again, if the new program doesn't have that many, default to the highest number of available periods.

5. I am having a hard time detecting the exact pattern, but sometimes -- I think it's with the Most Recent IPTT, not sure about TvA -- I'll enter in the exact number of available periods and it'll return LESS than that. So I will enter 7 tri-annual periods, having checked that there are exactly 7, and it'll switch to 5.

**Comment by camgnostic** [comment]
I think I've addressed all of these... but I have questions about #5 - could not reproduce... when you find it on qa can you link it here, @jennyhavah ?

**Comment by jennyhavah** [comment]
@camgnostic Still having some issues. Let me know if I've created a rat's nest of problems with this ticket and you recommend a different approach -- this ticket is not a must have, and I don't want you spending days on it...

**1. TvA IPTT:** If I switch between a non-time-aware frequency like Midline/Endline to a time-aware frequency, both radio buttons are unselected and it's _not_ showing all. Like, if I switch from M/E to Annual for Ann Viv Ansanmn, it'll show me Years 1 and 2 but not 3. If I do it with the RF builder program, it shows me years 1 and 2 but not 3, 4, and 5.

**Both types:** When I open a program that has ended in Show All mode, then type in a number of periods greater than the total, the Most Recent box remains blank and the Most Recent radio button is not selected.

**Comment by camgnostic** [comment]
> 1. TvA IPTT: If I switch between a non-time-aware frequency like Midline/Endline to a time-aware frequency, both radio buttons are unselected and it's not showing all. Like, if I switch from M/E to Annual for Ann Viv Ansanmn, it'll show me Years 1 and 2 but not 3. If I do it with the RF builder program, it shows me years 1 and 2 but not 3, 4, and 5.

What behavior would you prefer?  Should it just assume you want "Show all"?  A certain number of most recent?  It's an unclear condition (Mid/End or LoP have no concept of "show all" or "most recent" so it's a bit of an undefined state.

**Comment by jennyhavah** [comment]
@camgnostic I'd like to keep the behavior we have on production. If you switch from LoP-only or Midline/Endline to a time-aware frequency, it defaults to "Show all". The "Show all" radio button is selected and all data is included.

**Comment by jennyhavah** [comment]
@camgnostic We're SO close. I found an odd edge case.

This is the Target vs Actuals IPTT. Try this one: https://tola-activity-qa.mercycorps.org/indicators/iptt_report/98/targetperiods/?frequency=6&start=0&end=9

1. Type in a number larger than the total available periods. 
2. Note that it resets to 10, which is cool. (Alternately, you could just type "10")
3. Now, switch to LoP-only. 
4. Note that the "Most recent" radio button remains selected with the number 10 inside.

![image](https://user-images.githubusercontent.com/33670923/59726211-997aa200-91e5-11e9-9905-e359dfacedf8.png)

My expectation is that the Most recent field clears. And that is what normally happens, if I type in anything _less than_ the total number of available periods into Most recent.  But if it's _exactly_ the right number available, it doesn't clear.

**Comment by camgnostic** [comment]
That makes sense - I had to put a lot of weird logic in place to "latch" the most recent count on in the case where both "all indicators are shown" and "the most recent x indicators are shown" is true - one more check (has to be time-aware) is no problem

**Comment by jennyhavah** [comment]
Looks good! The "Most recent" field is clearing as expected when I switch from a time-aware to non-aware frequency.
